export const SET_TASK = "SET_TASK",
  SET_TASK_ERROR = "SET_TASK_ERROR",
  SET_SELECTED_TASK = "SET_SELECTED_TASK",
  SET_CLICKED_TASK_CLASS = "SET_CLICKED_TASK_CLASS";

export type TaskActionType =
  | "SET_TASK"
  | "SET_TASK_ERROR"
  | "SET_CLICKED_TASK_CLASS"
  | "SET_SELECTED_TASK";
